server:
  port: 8081
#  servlet:
#    context-path: /lucky


#spring:
#  profiles:
#    active: sit
spring:
  thymeleaf:
    cache: false
---
# yml \u6587\u6863\u5757
#spring:
#  profiles:
#    default: sit
#  mvc:
#    static-path-pattern: "/resources/**"
#  web:
#    resources:
#      add-mappings: true
#server:
#  port: 8080
#logging:
#  level:
#    com: info
#  file:
#    path will not effective if setup name
#    path: D:\
#    name: core.log

#person:
#  lastName: ding
#  age: ${random.int}
#  boss: false
#  birth: 2020/05/22
#  maps: {k1 : v1, k2 : v2}
#  lists:
#    - aaa
#    - bbb
#  dog:
#    name: ${person.lastName:lucky}'s dog - kele
#    age: 3